const express = require('express');
const PDFDocument = require('pdfkit');
const QRCode = require('qrcode');
const pool = require('../config/db');
const { requireAuth } = require('../middleware/auth');
require('dotenv').config();

const router = express.Router();

async function getOwnContribution(contributionId, userId) {
  const [rows] = await pool.query(
    `SELECT c.*, p.name AS plan_name, p.tagline, u.full_name, u.email
     FROM contributions c
     JOIN plans p ON p.id = c.plan_id
     JOIN users u ON u.id = c.user_id
     WHERE c.id = ? AND c.user_id = ?`,
    [contributionId, userId]
  );
  return rows[0] || null;
}

// GET /api/contributions/:id/agreement — a simple PDF partnership agreement
router.get('/:id/agreement', requireAuth, async (req, res) => {
  const c = await getOwnContribution(req.params.id, req.user.id);
  if (!c) return res.status(404).json({ error: 'Contribution not found.' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=agreement-${c.id}.pdf`);

  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(res);

  doc.fontSize(20).fillColor('#1F3A2E').text('Ceylon Green Life Plantation', { align: 'center' });
  doc.fontSize(11).fillColor('#666').text('Agricultural Partnership Agreement (demo document)', { align: 'center' });
  doc.moveDown(2);

  doc.fontSize(12).fillColor('#000');
  doc.text(`Agreement Reference: CGLP-${String(c.id).padStart(6, '0')}`);
  doc.text(`Date issued: ${new Date().toISOString().slice(0, 10)}`);
  doc.moveDown();

  doc.fontSize(14).fillColor('#1F3A2E').text('Contributor');
  doc.fontSize(12).fillColor('#000');
  doc.text(`Name: ${c.full_name}`);
  doc.text(`Email: ${c.email}`);
  doc.moveDown();

  doc.fontSize(14).fillColor('#1F3A2E').text('Partnership Details');
  doc.fontSize(12).fillColor('#000');
  doc.text(`Plan: ${c.plan_name} (${c.tagline})`);
  doc.text(`Contribution amount: Rs. ${Number(c.amount).toLocaleString()}`);
  doc.text(`Locked-in monthly rate: ${(c.monthly_rate * 100).toFixed(2)}%`);
  doc.text(`Term: ${c.duration_months} months`);
  doc.text(`Start date: ${c.start_date}`);
  doc.text(`Status: ${c.status}`);
  doc.moveDown(2);

  doc.fontSize(10).fillColor('#888').text(
    'This document is generated by a student/academic demo project modelled on ' +
    'a real company\'s publicly described services. It is not a legally binding ' +
    'agreement and does not represent a real financial commitment.',
    { align: 'left' }
  );

  doc.end();
});

// GET /api/contributions/:id/certificate — a certificate PDF with an embedded QR code
router.get('/:id/certificate', requireAuth, async (req, res) => {
  const c = await getOwnContribution(req.params.id, req.user.id);
  if (!c) return res.status(404).json({ error: 'Contribution not found.' });

  const verifyUrl = `${process.env.FRONTEND_URL || 'http://localhost:5173'}/verify/${c.id}`;
  const qrDataUrl = await QRCode.toDataURL(verifyUrl, { margin: 1, width: 200 });
  const qrBuffer = Buffer.from(qrDataUrl.split(',')[1], 'base64');

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=certificate-${c.id}.pdf`);

  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  doc.pipe(res);

  doc.rect(0, 0, doc.page.width, doc.page.height).fill('#F3F6F1');
  doc.rect(30, 30, doc.page.width - 60, doc.page.height - 60).lineWidth(2).stroke('#C9A227');

  doc.fillColor('#1F3A2E').fontSize(24).text('Certificate of Contribution', 0, 90, { align: 'center' });
  doc.fontSize(11).fillColor('#6B4226').text('Ceylon Green Life Plantation — student demo project', { align: 'center' });

  doc.moveDown(3);
  doc.fillColor('#000').fontSize(14).text(`This certifies that`, { align: 'center' });
  doc.fontSize(20).fillColor('#C43F58').text(c.full_name, { align: 'center' });
  doc.fontSize(14).fillColor('#000').text(
    `has contributed Rs. ${Number(c.amount).toLocaleString()} to the`,
    { align: 'center' }
  );
  doc.fontSize(16).fillColor('#1F3A2E').text(c.plan_name, { align: 'center' });
  doc.fontSize(12).fillColor('#000').text(
    `at a locked-in monthly rate of ${(c.monthly_rate * 100).toFixed(2)}% for ${c.duration_months} months.`,
    { align: 'center' }
  );

  doc.moveDown(2);
  const qrX = doc.page.width / 2 - 60;
  doc.image(qrBuffer, qrX, doc.y, { width: 120 });
  doc.moveDown(9);
  doc.fontSize(9).fillColor('#888').text('Scan to verify this contribution', { align: 'center' });
  doc.text(`Reference: CGLP-${String(c.id).padStart(6, '0')}`, { align: 'center' });

  doc.end();
});

// GET /api/verify/:id — public verification endpoint the QR code points to
router.get('/verify/:id', async (req, res) => {
  const [rows] = await pool.query(
    `SELECT c.id, c.amount, c.status, c.start_date, p.name AS plan_name, u.full_name
     FROM contributions c
     JOIN plans p ON p.id = c.plan_id
     JOIN users u ON u.id = c.user_id
     WHERE c.id = ?`,
    [req.params.id]
  );
  if (rows.length === 0) return res.status(404).json({ error: 'No contribution found for this certificate.' });

  const c = rows[0];
  res.json({
    valid: true,
    reference: `CGLP-${String(c.id).padStart(6, '0')}`,
    holderName: c.full_name,
    plan: c.plan_name,
    amount: Number(c.amount),
    status: c.status,
    startDate: c.start_date
  });
});

module.exports = router;
